# 1. Assessor and analyst work

## 1.0. Rating and criteria

Please [open this document](https://static.googleusercontent.com/media/guidelines.raterhub.com/en//searchqualityevaluatorguidelines.pdf)
and study chapters 13.0-13.4. Your task will be to assess the organic answers of search engines given the same query.

## 1.1. Explore the page

For the following search engines:
- https://duckduckgo.com/
- https://www.bing.com/
- https://ya.ru/
- https://www.google.com/

Perform the same query: "**How to get from Kazan to Voronezh**".

Discuss with your TA the following:
1. Which elements you may identify at SERP? Ads, snippets, blends from other sources, ...?
2. Where are organic results? How many of them are there?

## 1.2. Rate the results of the search engine

If there are many of you in the group, assess all search engines, otherwise choose 1 or 2. There should be no less than 5 of your for each search engine. Use the scale from the handbook, use 0..4 numerical equivalents for `[FailsM, SM, MM, HM, FullyM]`. 

Compute:
- average relevance and standard deviation for each SERP element.
- [Fleiss kappa score](https://en.wikipedia.org/wiki/Fleiss%27_kappa#Worked_example) for your group. Use [this implementation](https://www.statsmodels.org/dev/generated/statsmodels.stats.inter_rater.fleiss_kappa.html).
- [Kendall rank coefficient](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient) for some pairs in your group. Use [this implementation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html).

Discuss numerical results. Did you agree on the relevance? Did you agree on the rank? What is the difference?

In [8]:
import numpy as np
# example input by users
# 0 - fails to meet
# 1 - slightly meets
# 2 - moderately meets
# 3 - highly meets
# 4 - fully meets

ranking_data = np.array([
    [4, 3, 4, 0, 1, 1, 1, 0, 1, 1, 1, 0], # assessor 1 relevance
    [4, 3, 3, 0, 2, 1, 1, 1, 2, 1, 1, 1], # 2
    [4, 4, 3, 4, 4, 3, 3, 3, 2, 2, 2, 2],
    [4, 4, 4, 4, 2, 3, 3, 2, 3, 3, 3, 1],
    [4, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 3],
    [3, 3, 3, 3, 2, 2, 2, 3, 2, 2, 2, 3],
    [1, 4, 4, 1, 2, 2, 2, 1, 2, 2, 2, 0],
    [1, 3, 4, 4, 2, 2, 2, 2, 2, 1, 1, 1],
    [4, 3, 4, 3, 3, 2, 2, 2, 1, 0, 1, 0],
    [3, 3, 4 ,3, 4, 3 ,4 ,3 ,2, 4 ,2, 0],
    [1, 4, 4, 1, 1, 2, 2, 1, 2, 2, 2, 0],
    [1, 4, 3, 1, 4, 3, 1, 3, 3, 3, 3, 2]
])

Averages and standard deviations per item.

In [10]:
# TODO your code here
for i, row in enumerate(ranking_data):
    avg = np.mean(row, axis=0)
    std = np.std(row, axis=0)
    print(f"{i} relevance {avg:.2f} ± {std:.3f}")

0 relevance 1.42 ± 1.382
1 relevance 1.67 ± 1.106
2 relevance 3.00 ± 0.816
3 relevance 3.00 ± 0.913
4 relevance 2.92 ± 0.954
5 relevance 2.50 ± 0.500
6 relevance 1.92 ± 1.115
7 relevance 2.08 ± 1.037
8 relevance 2.08 ± 1.320
9 relevance 2.92 ± 1.115
10 relevance 1.83 ± 1.143
11 relevance 2.58 ± 1.037


Fleiss kappa score

In [ ]:
!pip install statsmodels

In [13]:
from statsmodels.stats.inter_rater import aggregate_raters, fleiss_kappa

# TODO your code here
agrmnt, cats = aggregate_raters(data=ranking_data.T, n_cat=5)
kappa = fleiss_kappa(table=agrmnt)

print(f"Agreement matrix:\n {agrmnt}")
print(f"Categories: {cats}")
print(f"Kappa: {kappa}")

Agreement matrix:
 [[0 4 0 2 6]
 [0 0 0 6 6]
 [0 0 0 4 8]
 [2 3 0 3 4]
 [0 2 6 1 3]
 [0 2 6 4 0]
 [0 3 6 2 1]
 [1 3 3 4 1]
 [0 2 8 2 0]
 [1 3 5 2 1]
 [0 4 6 2 0]
 [5 3 2 2 0]]
Categories: [0 1 2 3 4]
Kappa: 0.11603214841929356


Kendall tau score is pairwise. Compare one to another.

In [21]:
from scipy.stats import kendalltau

# TODO your code here
for i in range(len(ranking_data)):
    for j in range(len(ranking_data)):
        print(kendalltau(ranking_data[i], ranking_data[j]))

SignificanceResult(statistic=1.0, pvalue=0.00014831835432048583)
SignificanceResult(statistic=0.7918385252742848, pvalue=0.002308899433177536)
SignificanceResult(statistic=0.23159177829329275, pvalue=0.3839276075670829)
SignificanceResult(statistic=0.6042978219198488, pvalue=0.021505202991850325)
SignificanceResult(statistic=0.0683408533502272, pvalue=0.8024346036598436)
SignificanceResult(statistic=0.0, pvalue=1.0)
SignificanceResult(statistic=0.6382978723404256, pvalue=0.015451580464168668)
SignificanceResult(statistic=0.10418927964135326, pvalue=0.6918258173005736)
SignificanceResult(statistic=0.48300725250494714, pvalue=0.056657117526651785)
SignificanceResult(statistic=0.31256783892405976, pvalue=0.23438633928570252)
SignificanceResult(statistic=0.6042978219198488, pvalue=0.021505202991850325)
SignificanceResult(statistic=0.2127659574468085, pvalue=0.4195477953373796)
SignificanceResult(statistic=0.7918385252742848, pvalue=0.002308899433177536)
SignificanceResult(statistic=1.0, pv

In [ ]:
import seaborn as sns

sns.pairplot()

# 2. Engineer work

You will create a bucket of URLs which are relevant for the query **"free cloud git"**. Then you will automate the search procedure using https://serpapi.com/, or https://developers.google.com/custom-search/v1/overview, or whatever.

Then you will compute MRR@10 and Precision@10.

## 2.1. Build your bucket here

In [22]:
rel_bucket = [
    "github.com",
    "gitpod.io",
    "gitflic.ru",
    "git-scm.com",
    "gitlab.com",
    "git-tower.com",
    "azure.microsoft.com",
    "gitea.io",
]

query = "free git cloud"

## 2.2. Relevance assessment

Write the code to check that the obtained document is relevant (True) or not (False).

In [25]:
import json

# Opening JSON file
with open('sample.json', 'r') as openfile:
    # Reading from json file
    js = json.load(openfile)

print(js)
print(type(js))

{'search_metadata': {'id': '63e9f82ad5a531b7621ac076', 'status': 'Success', 'json_endpoint': 'https://serpapi.com/searches/3ff401fc84e9a74c/63e9f82ad5a531b7621ac076.json', 'created_at': '2023-02-13 08:43:22 UTC', 'processed_at': '2023-02-13 08:43:22 UTC', 'google_url': 'https://www.google.com/search?q=free+git+cloud&oq=free+git+cloud&gl=us&sourceid=chrome&ie=UTF-8', 'raw_html_file': 'https://serpapi.com/searches/3ff401fc84e9a74c/63e9f82ad5a531b7621ac076.html', 'total_time_taken': 5.76}, 'search_parameters': {'engine': 'google', 'q': 'free git cloud', 'google_domain': 'google.com', 'hl': 'en', 'gl': 'us', 'device': 'desktop'}, 'search_information': {'organic_results_state': 'Results for exact spelling', 'query_displayed': 'free git cloud', 'total_results': 43800000, 'time_taken_displayed': 0.39, 'menu_items': [{'position': 1, 'title': 'All'}, {'position': 2, 'title': 'Images', 'link': 'https://www.google.com/search?q=free+git+cloud&ucbcb=1&gl=us&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiY36

In [35]:
def is_rel(resp_url):
    # TODO your code here
    for link in rel_bucket:
        if link in resp_url:
            return True
    return False

## 2.3. Automation

Get search results from the automation tool you use.

In [36]:
rels = []

# Your code here
for result in js["organic_results"]:
    print(result['position'], result['title'])
    print(result['link'])
    print(is_rel(result['link']))
    rels.append(int(is_rel(result['link'])))
    print()

1 6 places to host your git repository - Opensource.com
https://opensource.com/article/18/8/github-alternatives
False

2 Bitbucket | Git solution for teams using Jira
https://bitbucket.org/product
False

3 Gitpod: Always ready to code.
https://www.gitpod.io/
True

4 GitLab: The DevSecOps Platform
https://about.gitlab.com/
True

5 GitHub: Let's build from here · GitHub
https://github.com/
True

6 14 Git Hosting Services Compared | Tower Blog
https://www.git-tower.com/blog/git-hosting-services-compared/
True

7 Top GitHub Alternatives to Host Your Open Source Projects
https://itsfoss.com/github-alternatives/
False

8 Git
https://git-scm.com/
True

9 Top 10 best Git hosting solutions and services in 2021
https://www.devopsschool.com/blog/top-5-git-hosting-solutions/
False

10 15 Best Github Alternatives in 2023 - Guru99
https://www.guru99.com/github-alternative.html
False



In [37]:
rels

[0, 0, 1, 1, 1, 1, 0, 1, 0, 0]

[Resource I found](https://gist.github.com/bwhite/3726239)

## 2.4. MRR

Compute MRR:

In [42]:
def mrr(list_of_lists, k=10):
    # todo your code here
    rel = 0
    for lst in list_of_lists:
        if 1 not in lst:
            rel += 1 / (k + 1)
        else:
            rel += 1 / (lst.index(1) + 1)

    mean_rel = rel/len(list_of_lists)
    return mean_rel

In [43]:
mrr([rels]) # BTW, why do I wrap the list into additional brackets? :)

0.3333333333333333

## 2.5. Precision
Compute mean precision:

In [44]:
def mp(list_of_lists, k=10):
    # todo your code here
    prec = 0
    for lst in list_of_lists:
        prec += sum(lst) / k

    mean_prec = prec/len(list_of_lists)
    return mean_prec

In [45]:
mp([rels])

0.5